### ISSUE TITLE
npm run test - ERROR

### ISSUE THREAD

**Issue by SvenMeyer** [adrianmcli/truffle-react#14]
`sum@XPS15 ~/DEV/truffle-react/client $ npm run test

> client@0.1.0 test /home/sum/DEV/truffle-react/client
> react-scripts test --env=jsdom

internal/fs/watchers.js:167
    throw error;
    ^

Error: ENOSPC: no space left on device, watch '/home/sum/DEV/truffle-react/client/node_modules/async-each'
    at FSWatcher.start (internal/fs/watchers.js:161:26)
    at Object.watch (fs.js:1218:11)
    at NodeWatcher.watchdir (/home/sum/DEV/truffle-react/client/node_modules/sane/src/node_watcher.js:150:20)
    at Walker.<anonymous> (/home/sum/DEV/truffle-react/client/node_modules/sane/src/node_watcher.js:374:12)
    at Walker.emit (events.js:182:13)
    at /home/sum/DEV/truffle-react/client/node_modules/walker/lib/walker.js:69:16
    at go$readdir$cb (/home/sum/DEV/truffle-react/client/node_modules/graceful-fs/graceful-fs.js:149:14)
    at FSReqWrap.oncomplete (fs.js:139:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! client@0.1.0 test: `react-scripts test --env=jsdom`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the client@0.1.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sum/.npm/_logs/2018-08-11T11_18_32_643Z-debug.log`

**Comment by adrianmcli** [comment]
> Error: ENOSPC: no space left on device, watch '/home/sum/DEV/truffle-react/client/node_modules/async-each'

It sounds like your device is out of space. Maybe this issue is relevant for you? https://github.com/npm/npm/issues/1131

**Comment by SvenMeyer** [comment]
I had Visual Studio Code running at the same time, which (as far as I remember now) surprisingly showed a message that it had too many files to watch. I did not resolve that problem yet, but the test is now running fine with node 10.8.0 , node v8.11.3 (npm v5.6.0) complained ...
`    The module '/home/sum/DEV/truffle-react/client/node_modules/scrypt/build/Release/scrypt.node'
    was compiled against a different Node.js version using
    NODE_MODULE_VERSION 64. This version of Node.js requires
    NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
    the module (for instance, using `npm rebuild` or `npm install`).
`
