### ISSUE TITLE
Failed to load web3, accounts, or contract. Check console for details.

### ISSUE THREAD

**Issue by ZhBoKn** [adrianmcli/truffle-react#16]
i have install web3,truffle ,python and so on. 
npm run start  it works .but the edge tell me that Failed to load web3, accounts, or contract. Check console for details. and the console tells that No web3 instance injected, using Local web3.
i don't change any files.i have metamask ,but the port 8545 shows me that it can't connect.i have no idea,please help me! thanks

**Comment by adrianmcli** [comment]
This project is deprecated, please use this one: https://github.com/truffle-box/react-box/
