### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by fredfortier** [adrianmcli/truffle-react#6]
Could you please add a license file? Everything else looks great.

**Comment by adrianmcli** [comment]
@fredfortier Good idea. The official truffle boxes don't have a license file either, but maybe that information is covered in their other documentation? What kind of license would you suggest? My immediate reaction is to just throw in an MIT license.

**Comment by fredfortier** [comment]
I would suggest an MIT license as well. Thanks!

**Comment by adrianmcli** [comment]
Awesome :)
